export const EXTERNAL_PUBLISHED_PAGES=[
 {airline:'AC',origin:'TLV',destination:'YYZ',sourceUrl:'https://www.aircanada.com/en-ca/flights-from-tel-aviv',allDestinations:true},
 {airline:'TP',origin:'TLV',destination:'LIS',sourceUrl:'https://www.flytap.com/en_il/flights-from-tel-aviv',allDestinations:true},
 {airline:'PR',origin:'MNL',destination:'BKK',sourceUrl:'https://flights.philippineairlines.com/en-ph/flights-from-manila-to-bangkok'},
 {airline:'EI',origin:'DUB',destination:'AMS',sourceUrl:'https://www.aerlingus.com/en-ie/flights-from-dublin',allDestinations:true},
 {airline:'VS',origin:'TLV',destination:'LHR',sourceUrl:'https://flights.virginatlantic.com/en-il/flights-from-tel-aviv',allDestinations:true},
 {airline:'NZ',origin:'LAX',destination:'AKL',sourceUrl:'https://www.airnewzealand.com/flights/en-us/flights-from-los-angeles',allDestinations:true},
 {airline:'BT',origin:'TLV',destination:'RIX',sourceUrl:'https://www.airbaltic.com/en/flight-deals/flights-from-israel',allDestinations:true},
 {airline:'BT',origin:'RIX',destination:'TLV',sourceUrl:'https://www.airbaltic.com/en/flight-deals/flights-from-riga-to-tel-aviv'},
 {airline:'GQ',origin:'ATH',destination:'FCO',sourceUrl:'https://www.skyexpress.gr/en/flights-from-athens',allDestinations:true},
 {airline:'G3',origin:'CGH',destination:'GIG',sourceUrl:'https://www.voegol.com.br/en/flights-from-sao-paulo',allDestinations:true,origins:['CGH','GRU','SAO']},
 {airline:'ET',origin:'TLV',destination:'BKK',sourceUrl:'https://www.ethiopianairlines.com/en-il/',allDestinations:true},
 {airline:'CM',origin:'PTY',destination:'MCO',sourceUrl:'https://www.copaair.com/en/flights-from-panama-city',allDestinations:true},
 {airline:'AA',origin:'LAX',destination:'MEX',sourceUrl:'https://www.aa.com/en-us/flights-from-los-angeles-to-mexico-city'},
 {airline:'IB',origin:'MAD',destination:'TLV',sourceUrl:'https://www.iberia.com/es/cheap-flights/Madrid-Tel-Aviv/'},
 {airline:'A3',origin:'TLV',destination:'ATH',sourceUrl:'https://flights.aegeanair.com/en/flights-from-tel-aviv-to-athens'},
 {airline:'A3',origin:'ATH',destination:'TLV',sourceUrl:'https://flights.aegeanair.com/en/flights-from-athens-to-tel-aviv'},
 {airline:'A3',origin:'ATH',destination:'FCO',sourceUrl:'https://flights.aegeanair.com/en/flights-from-athens-to-rome'},
 {airline:'A3',origin:'FCO',destination:'ATH',sourceUrl:'https://flights.aegeanair.com/en/flights-from-rome-to-athens'},
 {"airline": "AC", "origin": "TLV", "destination": "YYZ", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-toronto"},
 {"airline": "AC", "origin": "TLV", "destination": "EWR", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-newark"},
 {"airline": "AC", "origin": "TLV", "destination": "YUL", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-montreal"},
 {"airline": "AC", "origin": "TLV", "destination": "YVR", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-vancouver"},
 {"airline": "AC", "origin": "TLV", "destination": "ORD", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-chicago"},
 {"airline": "AC", "origin": "TLV", "destination": "MCO", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-orlando"},
 {"airline": "TP", "origin": "TLV", "destination": "JFK", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-new-york"},
 {"airline": "TP", "origin": "TLV", "destination": "EWR", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-new-york"},
 {"airline": "TP", "origin": "TLV", "destination": "LIS", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-lisbon"},
 {"airline": "TP", "origin": "TLV", "destination": "FNC", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-funchal"},
 {"airline": "TP", "origin": "TLV", "destination": "MIA", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-miami"},
 {"airline": "TP", "origin": "TLV", "destination": "PDL", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-ponta-delgada"},
 {"airline": "TP", "origin": "TLV", "destination": "OPO", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-porto"},
 {"airline": "TP", "origin": "TLV", "destination": "IBZ", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-ibiza"},
 {"airline": "VS", "origin": "TLV", "destination": "JFK", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-new-york"},
 {"airline": "VS", "origin": "TLV", "destination": "LAS", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-las-vegas"},
 {"airline": "VS", "origin": "TLV", "destination": "MIA", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-miami"},
 {"airline": "VS", "origin": "TLV", "destination": "YYZ", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-toronto"},
 {"airline": "VS", "origin": "TLV", "destination": "IAD", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-washington-dc"},
 {"airline": "VS", "origin": "TLV", "destination": "LAX", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-los-angeles"},
 {"airline": "VS", "origin": "TLV", "destination": "ATL", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-atlanta"},
 {"airline": "VS", "origin": "TLV", "destination": "SEA", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-seattle"},
 {"airline": "VS", "origin": "TLV", "destination": "MCO", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-orlando"},
 {"airline": "VS", "origin": "TLV", "destination": "EWR", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-newark"},
 {"airline": "VS", "origin": "TLV", "destination": "BOS", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-boston"},
 {"airline": "VS", "origin": "TLV", "destination": "SFO", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-san-francisco"},
];
