export const EXTERNAL_PUBLISHED_PAGES=[
 {airline:'AC',origin:'TLV',destination:'YYZ',sourceUrl:'https://www.aircanada.com/en-ca/flights-from-tel-aviv',allDestinations:true},
 {airline:'TP',origin:'TLV',destination:'LIS',sourceUrl:'https://www.flytap.com/en_il/flights-from-tel-aviv',allDestinations:true},
 {airline:'PR',origin:'MNL',destination:'BKK',sourceUrl:'https://flights.philippineairlines.com/en-ph/flights-from-manila-to-bangkok'},
 {airline:'EI',origin:'DUB',destination:'AMS',sourceUrl:'https://www.aerlingus.com/en-ie/flights-from-dublin',allDestinations:true},
 {airline:'VS',origin:'TLV',destination:'LHR',sourceUrl:'https://flights.virginatlantic.com/en-il/flights-from-tel-aviv',allDestinations:true},
 {airline:'NZ',origin:'LAX',destination:'AKL',sourceUrl:'https://www.airnewzealand.com/flights/en-us/flights-from-los-angeles',allDestinations:true},
 {airline:'BT',origin:'TLV',destination:'RIX',sourceUrl:'https://www.airbaltic.com/en/flight-deals/flights-from-israel',allDestinations:true},
 {airline:'BT',origin:'RIX',destination:'TLV',sourceUrl:'https://www.airbaltic.com/en/flight-deals/flights-from-riga-to-tel-aviv'},
 {airline:'GQ',origin:'ATH',destination:'FCO',sourceUrl:'https://www.skyexpress.gr/en/flights-from-athens',allDestinations:true},
 {airline:'G3',origin:'CGH',destination:'GIG',sourceUrl:'https://www.voegol.com.br/en/flights-from-sao-paulo',allDestinations:true,origins:['CGH','GRU','SAO']},
 {airline:'ET',origin:'TLV',destination:'BKK',sourceUrl:'https://www.ethiopianairlines.com/en-il/',allDestinations:true},
 {airline:'CM',origin:'PTY',destination:'MCO',sourceUrl:'https://www.copaair.com/en/flights-from-panama-city',allDestinations:true},
 {airline:'AA',origin:'LAX',destination:'MEX',sourceUrl:'https://www.aa.com/en-us/flights-from-los-angeles-to-mexico-city'},
 {airline:'IB',origin:'MAD',destination:'TLV',sourceUrl:'https://www.iberia.com/es/cheap-flights/Madrid-Tel-Aviv/'},
 {airline:'A3',origin:'TLV',destination:'ATH',sourceUrl:'https://flights.aegeanair.com/en/flights-from-tel-aviv-to-athens'},
 {airline:'A3',origin:'ATH',destination:'TLV',sourceUrl:'https://flights.aegeanair.com/en/flights-from-athens-to-tel-aviv'},
 {airline:'A3',origin:'ATH',destination:'FCO',sourceUrl:'https://flights.aegeanair.com/en/flights-from-athens-to-rome'},
 {airline:'A3',origin:'FCO',destination:'ATH',sourceUrl:'https://flights.aegeanair.com/en/flights-from-rome-to-athens'},
 {"airline": "AC", "origin": "TLV", "destination": "YYZ", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-toronto"},
 {"airline": "AC", "origin": "TLV", "destination": "EWR", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-newark"},
 {"airline": "AC", "origin": "TLV", "destination": "YUL", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-montreal"},
 {"airline": "AC", "origin": "TLV", "destination": "YVR", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-vancouver"},
 {"airline": "AC", "origin": "TLV", "destination": "ORD", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-chicago"},
 {"airline": "AC", "origin": "TLV", "destination": "MCO", "sourceUrl": "https://www.aircanada.com/en-ca/flights-from-tel-aviv-to-orlando"},
 {"airline": "TP", "origin": "TLV", "destination": "JFK", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-new-york"},
 {"airline": "TP", "origin": "TLV", "destination": "EWR", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-new-york"},
 {"airline": "TP", "origin": "TLV", "destination": "LIS", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-lisbon"},
 {"airline": "TP", "origin": "TLV", "destination": "FNC", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-funchal"},
 {"airline": "TP", "origin": "TLV", "destination": "MIA", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-miami"},
 {"airline": "TP", "origin": "TLV", "destination": "PDL", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-ponta-delgada"},
 {"airline": "TP", "origin": "TLV", "destination": "OPO", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-porto"},
 {"airline": "TP", "origin": "TLV", "destination": "IBZ", "sourceUrl": "https://www.flytap.com/en_il/flights-from-tel-aviv-to-ibiza"},
 {"airline": "VS", "origin": "TLV", "destination": "JFK", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-new-york"},
 {"airline": "VS", "origin": "TLV", "destination": "LAS", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-las-vegas"},
 {"airline": "VS", "origin": "TLV", "destination": "MIA", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-miami"},
 {"airline": "VS", "origin": "TLV", "destination": "YYZ", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-toronto"},
 {"airline": "VS", "origin": "TLV", "destination": "IAD", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-washington-dc"},
 {"airline": "VS", "origin": "TLV", "destination": "LAX", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-los-angeles"},
 {"airline": "VS", "origin": "TLV", "destination": "ATL", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-atlanta"},
 {"airline": "VS", "origin": "TLV", "destination": "SEA", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-seattle"},
 {"airline": "VS", "origin": "TLV", "destination": "MCO", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-orlando"},
 {"airline": "VS", "origin": "TLV", "destination": "EWR", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-newark"},
 {"airline": "VS", "origin": "TLV", "destination": "BOS", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-boston"},
 {"airline": "VS", "origin": "TLV", "destination": "SFO", "sourceUrl": "https://flights.virginatlantic.com/en-il/flights-from-tel-aviv-to-san-francisco"},
 {"airline": "GQ", "origin": "ATH", "destination": "SKG", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-thessaloniki"},
 {"airline": "GQ", "origin": "ATH", "destination": "HER", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-heraklion"},
 {"airline": "GQ", "origin": "ATH", "destination": "CDG", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-paris"},
 {"airline": "GQ", "origin": "ATH", "destination": "CHQ", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-chania"},
 {"airline": "GQ", "origin": "ATH", "destination": "LGW", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-london"},
 {"airline": "GQ", "origin": "ATH", "destination": "AMS", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-amsterdam"},
 {"airline": "GQ", "origin": "ATH", "destination": "RHO", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-rhodes"},
 {"airline": "GQ", "origin": "ATH", "destination": "LCA", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-larnaca"},
 {"airline": "GQ", "origin": "ATH", "destination": "FCO", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-rome"},
 {"airline": "GQ", "origin": "ATH", "destination": "BCN", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-barcelona"},
 {"airline": "GQ", "origin": "ATH", "destination": "MXP", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-milan"},
 {"airline": "GQ", "origin": "ATH", "destination": "VIE", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-vienna"},
 {"airline": "GQ", "origin": "ATH", "destination": "MUC", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-munich"},
 {"airline": "GQ", "origin": "ATH", "destination": "PRG", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-prague"},
 {"airline": "GQ", "origin": "ATH", "destination": "BRU", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-brussels"},
 {"airline": "GQ", "origin": "ATH", "destination": "WAW", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-warsaw"},
 {"airline": "GQ", "origin": "ATH", "destination": "IST", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-istanbul"},
 {"airline": "GQ", "origin": "ATH", "destination": "MAD", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-madrid"},
 {"airline": "GQ", "origin": "ATH", "destination": "DUS", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-dusseldorf"},
 {"airline": "GQ", "origin": "ATH", "destination": "FRA", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-frankfurt"},
 {"airline": "GQ", "origin": "ATH", "destination": "LIS", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-lisbon"},
 {"airline": "GQ", "origin": "ATH", "destination": "JTR", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-santorini"},
 {"airline": "GQ", "origin": "ATH", "destination": "BER", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-berlin"},
 {"airline": "GQ", "origin": "ATH", "destination": "MJT", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-mytilene"},
 {"airline": "GQ", "origin": "ATH", "destination": "AXD", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-alexandroupoli"},
 {"airline": "GQ", "origin": "ATH", "destination": "TBS", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-tbilisi"},
 {"airline": "GQ", "origin": "ATH", "destination": "JKH", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-chios"},
 {"airline": "GQ", "origin": "ATH", "destination": "HAM", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-hamburg"},
 {"airline": "GQ", "origin": "ATH", "destination": "KGS", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-kos"},
 {"airline": "GQ", "origin": "ATH", "destination": "CFU", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-corfu"},
 {"airline": "GQ", "origin": "ATH", "destination": "TLV", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-tel-aviv"},
 {"airline": "GQ", "origin": "ATH", "destination": "LYS", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-lyon"},
 {"airline": "GQ", "origin": "ATH", "destination": "PAS", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-paros"},
 {"airline": "GQ", "origin": "ATH", "destination": "CAI", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-cairo"},
 {"airline": "GQ", "origin": "ATH", "destination": "JMK", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-mykonos"},
 {"airline": "GQ", "origin": "ATH", "destination": "JNX", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-naxos"},
 {"airline": "GQ", "origin": "ATH", "destination": "TIA", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-tirana"},
 {"airline": "GQ", "origin": "ATH", "destination": "SOF", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-sofia"},
 {"airline": "GQ", "origin": "ATH", "destination": "SMI", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-samos"},
 {"airline": "GQ", "origin": "ATH", "destination": "JIK", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-ikaria"},
 {"airline": "GQ", "origin": "ATH", "destination": "LXS", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-lemnos"},
 {"airline": "GQ", "origin": "ATH", "destination": "EFL", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-kefalonia"},
 {"airline": "GQ", "origin": "ATH", "destination": "ZTH", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-zakynthos"},
 {"airline": "GQ", "origin": "ATH", "destination": "AOK", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-karpathos"},
 {"airline": "GQ", "origin": "ATH", "destination": "JSI", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-skiathos"},
 {"airline": "GQ", "origin": "ATH", "destination": "MLO", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-milos"},
 {"airline": "GQ", "origin": "ATH", "destination": "JTY", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-astypalaia"},
 {"airline": "GQ", "origin": "ATH", "destination": "JSY", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-syros"},
 {"airline": "GQ", "origin": "ATH", "destination": "JKL", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-kalymnos"},
 {"airline": "GQ", "origin": "ATH", "destination": "KZI", "sourceUrl": "https://www.skyexpress.gr/en/flights-from-athens-to-kozani"},
];
