/**
 * Replays worker/test/fixtures/parity.json (generated by engine/tools/gen_parity_fixture.py from the
 * Python reference engine) through the TypeScript port. Regenerate the fixture after changing the
 * engine or config/*.json:  python3 engine/tools/gen_parity_fixture.py
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import bagFeesJson from "../../config/bag_fees.json";
import scoringJson from "../../config/scoring.json";
import { applyExtrasAndFx } from "../src/extras";
import { BAG_FEES, SCORING } from "../src/scoring.config";
import { fastestByDirection, matchesTimes, recommend, valueScore } from "../src/scoring";
import type { FxRates, Offer, RecKind, SearchRequest } from "../src/types";

const TOL = 0.01;

interface Scenario {
  name: string;
  request: SearchRequest;
  offers: Offer[];
  expected: {
    offers: { totalIls: number | null; extrasAmountIls: number; tags: string[]; score: number | null; matchesTimes: boolean }[];
    fastest: [number | null, number | null];
    cards: { offerIndex: number; kinds: RecKind[]; savingsVsRoundtripIls: number | null }[];
  };
}

interface Fixture {
  config: { scoring: Record<string, number>; bagFees: Record<string, unknown> };
  fx: FxRates;
  scenarios: Scenario[];
}

const fixture = JSON.parse(readFileSync(join(import.meta.dirname, "fixtures", "parity.json"), "utf-8")) as Fixture;

function near(actual: number | null, expected: number | null, label: string): void {
  if (expected === null || actual === null) {
    expect(actual, label).toBe(expected);
    return;
  }
  expect(Math.abs(actual - expected), `${label}: got ${actual}, want ${expected}`).toBeLessThanOrEqual(TOL);
}

describe("fixture", () => {
  it("has at least 200 scenarios", () => {
    expect(fixture.scenarios.length).toBeGreaterThanOrEqual(200);
  });

  it("was generated with the config the Worker currently ships (else regenerate it)", () => {
    const s = fixture.config.scoring;
    expect(s.night_departure_penalty_ils).toBe(SCORING.nightDeparturePenaltyIls);
    expect(s.night_start_hour).toBe(SCORING.nightStartHour);
    expect(s.night_end_hour).toBe(SCORING.nightEndHour);
    expect(s.stop_penalty_ils).toBe(SCORING.stopPenaltyIls);
    expect(s.duration_penalty_ils_per_hour).toBe(SCORING.durationPenaltyIlsPerHour);
    expect(fixture.config.bagFees).toEqual(bagFeesJson.fees);
    // The camelCase view must expose exactly the JSON file's numbers.
    expect(SCORING.nightDeparturePenaltyIls).toBe(scoringJson.night_departure_penalty_ils);
    for (const [airline, entry] of Object.entries(bagFeesJson.fees)) {
      expect(BAG_FEES[airline]?.checkedBag).toEqual(entry.checked_bag);
    }
  });
});

describe("Python parity", () => {
  for (const sc of fixture.scenarios) {
    it(sc.name, () => {
      // Fresh copy: applyExtrasAndFx mutates, and the scenario is replayed twice below.
      const offers = structuredClone(sc.offers);
      const req = sc.request;
      const exp = sc.expected;

      applyExtrasAndFx(offers, req, fixture.fx);
      const afterFirst = offers.map((o) => ({ total: o.totalIls, extras: o.extrasAmountIls, tags: [...o.tags] }));
      applyExtrasAndFx(offers, req, fixture.fx); // idempotent
      expect(offers.map((o) => ({ total: o.totalIls, extras: o.extrasAmountIls, tags: [...o.tags] }))).toEqual(afterFirst);

      expect(offers.length).toBe(exp.offers.length);
      offers.forEach((o, i) => {
        const e = exp.offers[i]!;
        near(o.totalIls, e.totalIls, `offer ${i} totalIls`);
        near(o.extrasAmountIls, e.extrasAmountIls, `offer ${i} extrasAmountIls`);
        expect(o.tags, `offer ${i} tags`).toEqual(e.tags);
        expect(matchesTimes(o, req), `offer ${i} matchesTimes`).toBe(e.matchesTimes);
      });

      const priced = offers.filter((o) => o.totalIls !== null);
      const fastest = fastestByDirection(priced);
      expect(fastest).toEqual(exp.fastest);
      offers.forEach((o, i) => {
        const e = exp.offers[i]!;
        if (e.score === null) return;
        near(valueScore(o, fastest), e.score, `offer ${i} score`);
      });

      const cards = recommend(offers, req);
      expect(cards.length, "card count").toBe(exp.cards.length);
      cards.forEach((c, i) => {
        const e = exp.cards[i]!;
        expect(offers.indexOf(c.offer), `card ${i} offer index`).toBe(e.offerIndex);
        expect(c.kinds, `card ${i} kinds`).toEqual(e.kinds);
        near(c.savingsVsRoundtripIls, e.savingsVsRoundtripIls, `card ${i} savings`);
      });
    });
  }
});
